import { QUARANTINE_INSPECTING_BODY } from './businessConstants'
import type { ImsState } from './types'

/**
 * Four shipments (SHP-2401–SHP-2404) only. Workflow: two Active with sales,
 * one awaiting inspection, one inspection completed (partial) pending release.
 */
export const buildInitialState = (): ImsState => ({
  users: [
    {
      userId: 'USR-IO',
      username: 'inv_officer',
      password: 'demo',
      displayName: 'Inventory Officer',
      role: 'INVENTORY_OFFICER',
      isActive: true,
    },
    {
      userId: 'USR-SO',
      username: 'sales',
      password: 'demo',
      displayName: 'Sales Officer',
      role: 'SALES_OFFICER',
      isActive: true,
    },
    {
      userId: 'USR-DO',
      username: 'distribution',
      password: 'demo',
      displayName: 'Distribution Officer',
      role: 'DISTRIBUTION_OFFICER',
      isActive: true,
    },
    {
      userId: 'USR-MG',
      username: 'mgmt_user',
      password: 'demo',
      displayName: 'Management User',
      role: 'MANAGEMENT',
      isActive: true,
    },
    {
      userId: 'USR-AD',
      username: 'sys_admin',
      password: 'demo',
      displayName: 'System Administrator',
      role: 'SYSTEM_ADMINISTRATOR',
      isActive: true,
    },
  ],
  varieties: [
    {
      varietyId: 'VAR-SPUNTA',
      varietyName: 'Spunta',
      category: 'Seed potato',
      originDefault: 'France',
    },
    {
      varietyId: 'VAR-CARA-SHE',
      varietyName: 'Cara Sheraton',
      category: 'Seed potato',
      originDefault: 'Scotland',
    },
    {
      varietyId: 'VAR-CARA-ELF',
      varietyName: 'Cara Elfanar',
      category: 'Seed potato',
      originDefault: 'France',
    },
    {
      varietyId: 'VAR-HERMES',
      varietyName: 'Hermes',
      category: 'Seed potato',
      originDefault: 'Scotland',
    },
  ],
  suppliers: [
    {
      supplierId: 'SUP_ELORN',
      supplierName: 'Elorn Plants',
      country: 'France',
      isActive: true,
    },
    {
      supplierId: 'SUP_SMILLIE',
      supplierName: 'J&E Smillie',
      country: 'Scotland',
      isActive: true,
    },
  ],
  customers: [],
  batches: [
    {
      batchId: 'B-2401',
      shipmentReference: 'SHP-2401',
      varietyId: 'VAR-SPUNTA',
      supplierId: 'SUP_ELORN',
      origin: 'France',
      storageCategory: 'Cold storage',
      shipmentDocumentNote: 'Attachment: SHP-2401-bol.pdf',
      proposedQty: 1200,
      approvedQty: 1200,
      remainingQty: 1100,
      receivedDate: '2026-01-12',
      submittedDate: '2026-01-12',
      batchStatus: 'Active',
      submittedByUserId: 'USR-IO',
      approvedByUserId: 'USR-MG',
      approvalDate: '2026-01-14',
    },
    {
      batchId: 'B-2402',
      shipmentReference: 'SHP-2402',
      varietyId: 'VAR-CARA-SHE',
      supplierId: 'SUP_SMILLIE',
      origin: 'Scotland',
      storageCategory: 'Cold storage',
      shipmentDocumentNote: 'Attachment: SHP-2402-coa.pdf',
      proposedQty: 900,
      approvedQty: 900,
      remainingQty: 750,
      receivedDate: '2026-01-18',
      submittedDate: '2026-01-18',
      batchStatus: 'Active',
      submittedByUserId: 'USR-IO',
      approvedByUserId: 'USR-MG',
      approvalDate: '2026-01-20',
    },
    {
      batchId: 'B-2403',
      shipmentReference: 'SHP-2403',
      varietyId: 'VAR-CARA-ELF',
      supplierId: 'SUP_ELORN',
      origin: 'France',
      storageCategory: 'Cold storage',
      shipmentDocumentNote: 'Attachment: SHP-2403-bol.pdf',
      proposedQty: 800,
      approvedQty: 0,
      remainingQty: 0,
      receivedDate: '2026-01-25',
      submittedDate: '2026-01-25',
      batchStatus: 'PendingAgriculturalQuarantine',
      submittedByUserId: 'USR-IO',
    },
    {
      batchId: 'B-2404',
      shipmentReference: 'SHP-2404',
      varietyId: 'VAR-HERMES',
      supplierId: 'SUP_SMILLIE',
      origin: 'Scotland',
      storageCategory: 'Cold storage',
      shipmentDocumentNote: 'Attachment: SHP-2404-bol.pdf',
      proposedQty: 700,
      approvedQty: 0,
      remainingQty: 0,
      receivedDate: '2026-02-01',
      submittedDate: '2026-02-01',
      batchStatus: 'InspectionCompleted',
      submittedByUserId: 'USR-IO',
      inspectionOutcome: 'PartiallyApproved',
      inspectionApprovedQtyTonnes: 600,
      inspectionRejectedQtyTonnes: 100,
      inspectingBody: QUARANTINE_INSPECTING_BODY,
      inspectionDate: '2026-03-18',
      quarantineApprovalDocumentNote: 'Quarantine approval: SHP-2404-aq-cert.pdf',
    },
  ],
  salesRecords: [
    {
      saleRecordId: 'SR-01',
      batchId: 'B-2401',
      varietyId: 'VAR-SPUNTA',
      saleDate: '2026-03-01',
      requestedQty: 150,
      confirmedQty: 150,
      dispatchedQty: 100,
      customerSegment: 'Farmers',
      customerName: 'Ahmed Hassan',
      expectedDispatchDate: '2026-03-15',
      status: 'PartiallyDispatched',
      createdByUserId: 'USR-SO',
    },
    {
      saleRecordId: 'SR-02',
      batchId: 'B-2402',
      varietyId: 'VAR-CARA-SHE',
      saleDate: '2026-03-02',
      requestedQty: 200,
      confirmedQty: 200,
      dispatchedQty: 150,
      customerSegment: 'Manufacturers',
      customerName: 'Egypt Foods',
      expectedDispatchDate: '2026-03-16',
      status: 'PartiallyDispatched',
      createdByUserId: 'USR-SO',
    },
    {
      saleRecordId: 'SR-03',
      batchId: 'B-2401',
      varietyId: 'VAR-SPUNTA',
      saleDate: '2026-03-03',
      requestedQty: 50,
      confirmedQty: 50,
      dispatchedQty: 0,
      customerSegment: 'Traders',
      customerName: 'Nile Delta Traders',
      expectedDispatchDate: '2026-03-20',
      status: 'Reserved',
      createdByUserId: 'USR-SO',
    },
    {
      saleRecordId: 'SR-04',
      batchId: 'B-2402',
      varietyId: 'VAR-CARA-SHE',
      saleDate: '2026-03-03',
      requestedQty: 50,
      confirmedQty: 50,
      dispatchedQty: 0,
      customerSegment: 'Agricultural Associations',
      customerName: 'Beheira Agricultural Association',
      expectedDispatchDate: '2026-03-22',
      status: 'Reserved',
      createdByUserId: 'USR-SO',
    },
  ],
  movements: [
    {
      movementId: 'MV-B2401-IA',
      batchId: 'B-2401',
      movementType: 'InboundApproval',
      quantity: 1200,
      movementDate: '2026-01-14T08:00:00.000Z',
      performedByUserId: 'USR-MG',
    },
    {
      movementId: 'MV-B2402-IA',
      batchId: 'B-2402',
      movementType: 'InboundApproval',
      quantity: 900,
      movementDate: '2026-01-20T08:00:00.000Z',
      performedByUserId: 'USR-MG',
    },
    {
      movementId: 'MV-SR01-RC',
      batchId: 'B-2401',
      saleRecordId: 'SR-01',
      movementType: 'ReservationCreated',
      quantity: 150,
      movementDate: '2026-03-01T10:00:00.000Z',
      performedByUserId: 'USR-SO',
    },
    {
      movementId: 'MV-SR02-RC',
      batchId: 'B-2402',
      saleRecordId: 'SR-02',
      movementType: 'ReservationCreated',
      quantity: 200,
      movementDate: '2026-03-02T10:00:00.000Z',
      performedByUserId: 'USR-SO',
    },
    {
      movementId: 'MV-SR03-RC',
      batchId: 'B-2401',
      saleRecordId: 'SR-03',
      movementType: 'ReservationCreated',
      quantity: 50,
      movementDate: '2026-03-03T11:00:00.000Z',
      performedByUserId: 'USR-SO',
    },
    {
      movementId: 'MV-SR04-RC',
      batchId: 'B-2402',
      saleRecordId: 'SR-04',
      movementType: 'ReservationCreated',
      quantity: 50,
      movementDate: '2026-03-03T11:15:00.000Z',
      performedByUserId: 'USR-SO',
    },
    {
      movementId: 'MV-SR01-DP',
      batchId: 'B-2401',
      saleRecordId: 'SR-01',
      movementType: 'Dispatch',
      quantity: 100,
      movementDate: '2026-03-10T06:00:00.000Z',
      performedByUserId: 'USR-DO',
    },
    {
      movementId: 'MV-SR02-DP',
      batchId: 'B-2402',
      saleRecordId: 'SR-02',
      movementType: 'Dispatch',
      quantity: 150,
      movementDate: '2026-03-11T06:00:00.000Z',
      performedByUserId: 'USR-DO',
    },
  ],
  audit: [],
})
